apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/microservices-fh-nestjs/image-repo/payments-ms
        name: payments-ms
        env:
        - name: PORT
          value: "3003"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: SUCCESS_URL
          value: http://localhost:3003/payments/success
        - name: CANCEL_URL
          value: http://localhost:3003/payments/cancel
        - name: SECRET_API_KEY
          valueFrom:
            secretKeyRef:
              name: payments-ms
              key: secret_api_key
        - name: ENDPOINT_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-ms
              key: endpoint_secret
        resources: {}
status: {}
