apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service
  name: service
spec:
  ports:
  - name: "3003"
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: payments-ms # This needs to aim to the deployment app name
  type: NodePort
status:
  loadBalancer: {}
