apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: products
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/microservices-fh-nestjs/image-repo/products-ms
        name: products-ms
        env: 
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          value: "file:./dev.db"
        resources: {}
status: {}
